/* Catálogo editable: nombre, descripción y precio viven aquí. */
const groups={
  hamburguesas:[['King Classic','Carne, queso, lechuga, tomate y salsa especial',6.99],['King Cheese','Carne a la parrilla con doble queso',7.49],['Bacon King','Bacon crujiente, queso y salsa ahumada',8.29],['Double King','Dos carnes, queso y pepinillos',9.49],['Crispy Burger','Pollo crispy, slaw y mayonesa de la casa',7.99],['BBQ King','Carne, cebolla y BBQ artesanal',8.49],['Mushroom Burger','Champiñones salteados y queso suizo',8.69],['Spicy King','Carne, jalapeños y salsa picante',8.29],['Premium King','Carne premium, rúcula y queso azul',10.99],['Triple King','Tres carnes para hambre de rey',12.49]],
  pollo:[['Crispy Chicken','Pechuga crujiente y ensalada fresca',7.49],['Chicken Classic','Pollo grillado y salsa especial',7.29],['Spicy Chicken','Pollo picante y pepinillos',7.69],['Chicken Bacon','Pollo, bacon y queso',8.49],['Chicken BBQ','Pollo glaseado con BBQ',7.99],['Chicken Cheese','Pollo y cheddar fundido',7.79],['Chicken Deluxe','Pollo, aguacate y lechuga',8.79],['Chicken Crunch','Tiras crispy extra crujientes',7.99],['Chicken Premium','Pollo premium y salsa trufada',9.49],['Chicken Supreme','Pollo, queso y cebolla caramelizada',9.79]],
  papas:[['Papas clásicas','Corte dorado y sal marina',2.99],['Papas grandes','Porción extra para compartir',4.29],['Papas con queso','Papas doradas con cheddar',4.49],['Papas con bacon','Bacon crocante y cheddar',5.29],['Papas BBQ','Salsa BBQ y cebolla crispy',4.79],['Papas Supreme','Queso, bacon y salsa especial',5.99]],
  bebidas:[['Coca-Cola','Refresco clásico bien frío',2.19],['Coca-Cola Zero','Todo el sabor, sin azúcar',2.19],['Sprite','Refresco cítrico refrescante',2.19],['Fanta','Refresco sabor naranja',2.19],['Agua','Agua mineral natural',1.69],['Té frío','Té de limón helado',2.49],['Limonada','Limón fresco y hierbabuena',2.99],['Batido de chocolate','Cremoso batido de cacao',4.49],['Batido de fresa','Batido de fresa natural',4.49],['Jugo natural','Jugo del día recién hecho',3.49]],
  postres:[['Brownie','Chocolate intenso y nueces',3.49],['Brownie con helado','Brownie tibio y vainilla',4.79],['Cheesecake','Cremoso cheesecake clásico',4.49],['Sundae de chocolate','Helado y salsa de chocolate',3.69],['Sundae de fresa','Helado y salsa de fresa',3.69],['Helado de vainilla','Copa de vainilla cremosa',2.99],['Helado de chocolate','Copa de cacao cremoso',2.99],['Tarta de manzana','Manzana especiada y masa crujiente',4.29],['Cookie King','Galleta gigante con chips',2.79],['Milkshake','Batido cremoso de la casa',4.99]],
  desayunos:[['Desayuno King','Huevos, papas y café',6.99],['Pancakes','Pancakes con miel de maple',4.99],['Pancakes con bacon','Pancakes, bacon y maple',6.29],['Huevos con tocino','Huevos al gusto con bacon',5.99],['Sándwich de desayuno','Huevo, queso y pan tostado',4.79],['Croissant','Croissant horneado del día',2.99],['Croissant de jamón y queso','Relleno de jamón y queso',4.29],['Tostadas','Tostadas con mantequilla y mermelada',3.49],['Omelette','Omelette de queso y vegetales',5.79],['Desayuno Premium','Desayuno completo para empezar',8.99]],
  cafe:[['Espresso','Café intenso de origen',1.99],['Americano','Café negro equilibrado',2.29],['Cappuccino','Espresso, leche y espuma',3.49],['Latte','Café suave con leche',3.59],['Latte vainilla','Latte con toque de vainilla',3.99],['Latte caramelo','Latte con caramelo',3.99],['Mocha','Café, chocolate y leche',4.19],['Chocolate caliente','Chocolate cremoso',3.49],['Café frío','Café helado y suave',3.79],['Frappé','Café frappé de la casa',4.49]]};
const categoryImages={hamburguesas:'1568901346375-23c9450c58cd',pollo:'1562967914-608f82629710',papas:'1573080496219-bb080dd4f877',bebidas:'1544145945-f90425340c7e',postres:'1551024506-0bccd828d307',desayunos:'1533089860892-a7c6f0a88666',cafe:'1495474472287-4d71bcdd2085'};
const products=Object.entries(groups).flatMap(([category,items])=>items.map(([name,description,price],i)=>({id:`${category}-${i}`,category,name,description,price,image:`https://images.unsplash.com/photo-${categoryImages[category]}?auto=format&fit=crop&w=700&q=80`})));
document.addEventListener('DOMContentLoaded',()=>{const root=document.querySelector('#products');if(!root)return;let filter='todos',query='';const labels={todos:'Todos',...Object.fromEntries(Object.keys(groups).map(k=>[k,k[0].toUpperCase()+k.slice(1)]))};document.querySelector('#filters').innerHTML=Object.entries(labels).map(([k,v])=>`<button data-filter="${k}" class="${k==='todos'?'active':''}">${v}</button>`).join('');function render(){const list=products.filter(p=>(filter==='todos'||p.category===filter)&&(`${p.name} ${p.description}`).toLowerCase().includes(query));root.innerHTML=list.length?list.map(p=>`<article class="product-card reveal"><img src="${p.image}" alt="Imagen demostrativa de ${p.name}"><div class="product-info"><span class="tag">${labels[p.category]}</span><h3>${p.name}</h3><p>${p.description}</p><div class="product-bottom"><strong>${KB.money(p.price)}</strong><div class="quantity"><button aria-label="Restar">−</button><output>1</output><button aria-label="Sumar">+</button></div></div><button class="add" data-id="${p.id}">Agregar al carrito <span>+</span></button></div></article>`).join(''):'<p class="empty">No encontramos productos con esa búsqueda.</p>';}
document.querySelector('#filters').onclick=e=>{if(e.target.dataset.filter){filter=e.target.dataset.filter;document.querySelectorAll('#filters button').forEach(b=>b.classList.toggle('active',b===e.target));render()}};document.querySelector('#search').oninput=e=>{query=e.target.value.toLowerCase().trim();render()};root.onclick=e=>{const q=e.target.closest('.quantity');if(q){const out=q.querySelector('output');out.value=Math.max(1,+out.value+(e.target.textContent==='+'?1:-1));return}const add=e.target.closest('.add');if(add){if(!KB.user){document.querySelector('#auth-modal').classList.add('show');return}const p=products.find(x=>x.id===add.dataset.id),qty=+add.closest('.product-card').querySelector('output').value,cart=KB.cart,old=cart.find(x=>x.id===p.id);old?old.qty+=qty:cart.push({...p,qty});KB.cart=cart;updateHeader();toast(`${p.name} se agregó al carrito`);}};render();});
